### ISSUE TITLE
Regarding the listing of community members

### ISSUE THREAD

**Issue by Ubugeeei** [oxc-project/oxc-project.github.io#17]
https://oxc-project.github.io/docs/guide/introduction.html#community

No, no, this isn't right. 
Since there are people who have contributed more significantly to the main project, 
I don't think it's appropriate for me to be included here ( ? )
It feels a bit self-serving to include myself. 😅 
I feel it would be better to either list other people as well, or remove my name.

@Boshen @NozomuIkuta

**Comment by Boshen** [comment]
It's probably just a placeholder, we can either:
* remove the whole list
* I find more people to add ... which I don't really have one, and I need to ask consensus for each person 😅

**Comment by Ubugeeei** [comment]
Since this page itself is public,
if it's meant to be a placeholder, at the very least it should be made clear as such.
What do you think? @NozomuIkuta 🤔

**Comment by NozomuIkuta** [comment]
@Boshen @Ubugeeei 

First of all, I never intend to treat me and @Ubugeeei prominent, and what I wanted to implement with "Community Members" section is like the below:

- https://v2.nuxt.com/teams
- https://github.com/vuejs/core#contribution

Then, since I didn't know @Boshen's thoughts about community management, [I confirmed it in the PR comment](https://github.com/oxc-project/oxc-project.github.io/pull/16#discussion_r1398423787) like below:

> Of course, only if you [@Boshen] are fine.
> I could redesign UI to show community members with smaller cards.

And the reason why I added me and @Ubugeeei only was that I just wanted to demonstrate what Team feature of VitePress looks like (since it's referred to in #3) with a logic to manage data, before making up all.

----

By the way, there are already [about 60 contributors of OXC core](https://github.com/oxc-project/oxc/graphs/contributors), so at least "the number of people to show" would be enough, and we could ask them with only one Issue comment whether it's fine to be listed up.

Another point based on which I guess @Ubugeeei feels humbled is that, the size of card UI is as large as core members like @Boshen. As I commented in the PR (see above), we could show just contributors' avatars only like Vue project does, which I believe is more suitable for showing about 60 people, and this way will match @Ubugeeei's feeling,

> It might be better not to specify actual account names.

---

Anyway, it's all up to @Boshen. 🙌
